### ISSUE TITLE
Create Wikipedia page for K6

### ISSUE THREAD

**Issue by StephenRadachy** [k6io/k6-docs#104]
We'd like to have k6 as a part of the load testing page on Wikipedia. The page maintainer would like to have a dedicated page per https://en.wikipedia.org/w/index.php?title=Load_testing&action=history. Once this happens, we should be able to add k6 to the load testing page and resolve https://github.com/loadimpact/k6/issues/301

**Comment by simskij** [comment]
Closing this. Does not really make sense to track it in the docs repo, especially as it's pending wikipedia.
